import os
import subprocess


def run_cellprofiler_by_cli(cp_exec_path, input_dir, overlay_dir, csv_dir,
                            pipeline_template_path=None, status_callback=None):
    """
    Quietly calls the local CellProfiler independent software via CLI to run analysis without relying on python-cellprofiler library.
    If pipeline_template_path is not specified, it will auto-search for pipeline_3D-1115.cppipe in script directory or current working directory.

    :param cp_exec_path: Absolute path to local CellProfiler executable (e.g. "C:/Program Files/CellProfiler/CellProfiler.exe")
    :param input_dir: Path to raw TIFF images for analysis
    :param overlay_dir: Output path for overlay images generated by Module 7, 9, 19
    :param csv_dir: Output path for CSV data generated by Module 23
    :param pipeline_template_path: Path to the .cppipe template file (Optional. If None, it will search for pipeline_3D-1115.cppipe automatically)
    :param status_callback: Callback function to stream real-time logs to the main GUI
    """

    def log(msg):
        if status_callback:
            status_callback(msg)
        else:
            print(msg)

    # 1. Verify input paths
    if not os.path.exists(input_dir):
        log(f"Error: Input path does not exist -> {input_dir}")
        return False

    for d in [overlay_dir, csv_dir]:
        if not os.path.exists(d):
            os.makedirs(d)

    # 2. Auto-locate the pipeline template file
    if pipeline_template_path is None:
        target_filename = "pipeline_3D-1115.cppipe"

        # Candidate Path 1: Directory containing this script (Recommended)
        script_dir = os.path.dirname(os.path.abspath(__file__))
        path_candidate_1 = os.path.join(script_dir, target_filename)

        # Candidate Path 2: Current working directory
        path_candidate_2 = os.path.join(os.getcwd(), target_filename)

        if os.path.exists(path_candidate_1):
            pipeline_template_path = path_candidate_1
            log(f"Auto-located Pipeline template (script directory): {pipeline_template_path}")
        elif os.path.exists(path_candidate_2):
            pipeline_template_path = path_candidate_2
            log(f"Auto-located Pipeline template (working directory): {pipeline_template_path}")
        else:
            log(f"Error: Failed to auto-locate template file {target_filename}.")
            log(f"Searched paths:\n 1. {path_candidate_1}\n 2. {path_candidate_2}")
            return False
    else:
        # Validate manual path provided by user
        if not os.path.exists(pipeline_template_path):
            log(f"Error: The specified Pipeline template does not exist -> {pipeline_template_path}")
            return False

    # 3. Read the .cppipe template and dynamically configure output paths
    temp_pipeline_path = os.path.join(os.path.dirname(pipeline_template_path), "temp_runtime_pipeline.cppipe")
    log("Parsing and dynamically configuring CellProfiler Pipeline paths...")

    try:
        with open(pipeline_template_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # String processing + Case-insensitive matching (.lower()) to identify replacement targets
        # This ensures strings like /CSV, /csv, or /Csv are correctly identified and replaced
        lines = content.splitlines()
        modified_lines = []
        for line in lines:
            if "Elsewhere...|" in line:
                parts = line.split("Elsewhere...|")
                line_lower = line.lower()

                if "overlay" in line_lower:
                    # Replace with the configured overlay directory
                    line = f"{parts[0]}Elsewhere...|{overlay_dir}"
                elif "csv" in line_lower:
                    # Replace with the configured CSV directory
                    line = f"{parts[0]}Elsewhere...|{csv_dir}"
            modified_lines.append(line)

        new_content = "\n".join(modified_lines)

        # Save the runtime pipeline configurations to a temporary file
        with open(temp_pipeline_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        log("Runtime Pipeline file configuration completed.")
    except Exception as e:
        log(f"Error configuring Pipeline template: {str(e)}")
        return False

    # 4. Construct CLI execution command
    cmd = [
        cp_exec_path,
        "-c",
        "-r",
        "-p", temp_pipeline_path,
        "-i", input_dir,
        "-o", csv_dir
    ]

    log("Launching background CellProfiler analysis task, please wait...")
    log(f"Command invoked: {' '.join(cmd)}")

    # 5. Run subprocess and capture live outputs
    try:
        # Start the process with subprocess.Popen to capture outputs in real-time
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,  # Redirect stderr to stdout
            text=True,
            bufsize=1,
            universal_newlines=True
        )

        # Forward logs back to GUI console in real-time
        while True:
            output = process.stdout.readline()
            if output == '' and process.poll() is not None:
                break
            if output:
                clean_output = output.strip()
                if clean_output:
                    log(f"[CellProfiler] {clean_output}")

        rc = process.poll()
        if rc == 0:
            log("🎉 CellProfiler data analysis completed successfully!")
            success = True
        else:
            log(f"❌ CellProfiler terminated abnormally, exit code: {rc}")
            success = False

    except Exception as e:
        log(f"Error running process: {str(e)}")
        success = False
    finally:
        # 6. Cleanup: Commented out to retain temp_runtime_pipeline.cppipe for manual verification
        pass

    return success